In [1]:
# Comparatif Numpy Array VS BuiLT-In List
import numpy as np

In [2]:
my_arr = np.arange(100000)

In [3]:
my_list = list(range(1000000))

In [18]:
# Multiplier par 2 et calculer le temps d'exécution
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 1 ms


In [19]:
%time for _ in range(10): my_list2 = [ x * 2 for x in my_list]

Wall time: 954 ms


In [21]:
"""   Ndarray""" 
#generate random data
data = np.random.randn(2,3)


In [22]:
data

array([[ 0.34990824,  0.51247143,  0.56809456],
       [-0.03673371,  0.30128526, -1.31294784]])

In [23]:
data * 10

array([[  3.49908238,   5.12471432,   5.68094559],
       [ -0.36733715,   3.01285264, -13.12947844]])

In [24]:
data + data

array([[ 0.69981648,  1.02494286,  1.13618912],
       [-0.07346743,  0.60257053, -2.62589569]])

In [27]:
# taille de chaque dimension
data.shape

(2, 3)

In [28]:
# type des données dans un array
data.dtype

dtype('float64')