In [1]:
import numpy as np

In [2]:
# Produit matriciel   (np.dot)
arr = np.random.randn(6,3)

In [3]:
arr

array([[-0.30482124,  0.78119834,  0.57845977],
       [ 2.37227367, -1.24530577,  1.24409617],
       [ 0.36252389, -0.21891979, -0.90455132],
       [ 0.4584942 , -1.32585474,  0.87892054],
       [ 2.43119642,  1.09189208, -1.18837733],
       [ 0.22619433,  2.04729529,  0.02886038]])

In [4]:
np.dot(arr.T,arr)

array([[ 12.02411876,  -0.7619016 ,  -0.03258239],
       [ -0.7619016 ,   9.35052032,  -3.30317919],
       [ -0.03258239,  -3.30317919,   4.88617898]])

In [11]:
#swapaxes : modifie l'axe ainsi que l'ordre deu reshape
arr = np.arange(2*4*3).reshape(2,4,3)

In [12]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [21]:
arr.swapaxes(0,2)

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [22]:
""" Ufunc : Universal Function """

' Ufunc : Universal Function '

In [25]:
#Suite de fonctions simples s'appliquant sur l'array
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Racine carrée
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [28]:
# Exponentielle
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [31]:
# Fonctions à plusieurs paramètres
x = np.random.randn(8)


In [32]:
x

array([ 0.80378038, -2.46776455, -1.00288838, -1.64409091,  0.86309506,
       -1.98453027, -1.43126327,  0.05096502])

In [33]:
y = np.random.randn(8)

In [34]:
y

array([ 1.52231378, -0.39014201,  0.34465107,  0.15047042, -1.29767782,
       -0.68030597, -0.18616148, -1.07184789])

In [36]:
#maximum entre 2 elts de chaque array
np.maximum(x,y)

array([ 1.52231378, -0.39014201,  0.34465107,  0.15047042,  0.86309506,
       -0.68030597, -0.18616148,  0.05096502])

In [39]:
# Renvoyer la partie entière et fractionnelle d'un nombre dans 2 arrays séparées (np.modf())
arr = np.random.randn(7)*10

In [40]:
arr

array([ 20.10523601, -19.56563613,  -5.0582739 ,  -1.18633303,
         4.40713881,  11.40252501,  -4.73239623])

In [41]:
entiere,apres_virgule = np.modf(arr)

In [42]:
entiere

array([ 0.10523601, -0.56563613, -0.0582739 , -0.18633303,  0.40713881,
        0.40252501, -0.73239623])

In [43]:
apres_virgule

array([ 20., -19.,  -5.,  -1.,   4.,  11.,  -4.])

In [44]:
""" Exprimer une condition logique """

' Exprimer une condition logique '

In [45]:
#2 arrays de chiffres(xarr,yarr), 1 de booleans (cond) : choisir un elt de xarr si elt cond == true sinon depuis yarr
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

In [46]:
yarr = np.array([2.1,2.2,2.3,2.4,2.5])

In [47]:
cond = np.array([True,False,True,True,False])

In [48]:
# method np.where()
result = np.where(cond,xarr,yarr)

In [49]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [50]:
# Remplacer toutes les données négatives pas -2 et positives par 2
arr = np.random.randn(4,4)

In [51]:
arr

array([[-0.21181096, -0.8527891 ,  0.36697102,  0.5302848 ],
       [-0.76254844, -1.4611373 ,  0.39466756, -0.54844454],
       [ 0.23038357, -1.20292347, -1.21229595, -1.39662021],
       [-1.33261341,  0.37888964, -1.03167051,  0.38438033]])

In [52]:
np.where(arr > 0,2,-2)

array([[-2, -2,  2,  2],
       [-2, -2,  2, -2],
       [ 2, -2, -2, -2],
       [-2,  2, -2,  2]])

In [53]:
#remplacer uniquement les valeurs positives par 2
np.where( arr >0, 2, arr)

array([[-0.21181096, -0.8527891 ,  2.        ,  2.        ],
       [-0.76254844, -1.4611373 ,  2.        , -0.54844454],
       [ 2.        , -1.20292347, -1.21229595, -1.39662021],
       [-1.33261341,  2.        , -1.03167051,  2.        ]])

In [54]:
""" Methodes mathematiques et statistiques """

' Methodes mathematiques et statistiques '

In [55]:
arr = np.random.randn(5,4)

In [56]:
arr

array([[ 0.65612507,  0.79826725, -1.31709201,  0.12944957],
       [-0.70890197,  0.06181775,  0.16600109, -0.24691879],
       [ 0.15138891, -0.1201118 ,  1.96872558, -0.10170208],
       [ 1.98033102,  1.0219899 , -1.36327506,  0.24268597],
       [ 2.55926723, -0.64887907, -0.84462728,  1.3806347 ]])

In [57]:
arr.mean()

0.28825879751302541

In [58]:
np.mean(arr)

0.28825879751302541

In [59]:
arr.sum()

5.7651759502605087

In [64]:
# on peut calculer le mean ou sum selon l'axe (0 : rows, 1 : columns)
arr.mean(axis=1)

array([ 0.06668747, -0.18200048,  0.47457515,  0.47043296,  0.61159889])

In [61]:
arr.mean(axis=0)

array([ 0.92764205,  0.22261681, -0.27805354,  0.28082987])

In [63]:
arr.sum(axis=0)

array([ 4.63821024,  1.11308403, -1.39026769,  1.40414937])

In [65]:
#somme cumulée
arr = np.arange(8)

In [66]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [73]:
# somme cumulée pour pour un array multidimmensionnel
arr = np.arange(3*3).reshape(3,3)

In [74]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [78]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [79]:
""" Methodes pour les arrays booleens """


' Methodes pour les arrays booleens '

In [80]:
#compter le nombre de True
arr = np.random.randn(100)

In [81]:
(arr >0).sum()

53

In [83]:
# Any : verifie si il y a un ou plus de True dans un array
bools = np.array([False,False,True,False])

In [84]:
bools.any()

True

In [85]:
#All : verifie si ils sont tous True
bools.all()

False

In [86]:
""" Tri """

' Tri '

In [87]:
arr = np.random.randn(6)

In [88]:
arr

array([ 0.0324742 , -1.78179049, -0.0387971 , -0.9985506 , -0.90832027,
       -0.71588247])

In [89]:
arr.sort()

In [90]:
arr

array([-1.78179049, -0.9985506 , -0.90832027, -0.71588247, -0.0387971 ,
        0.0324742 ])

In [92]:
# tri multidimmensionnel
arr = np.random.randn(5,3)

In [93]:
arr

array([[ 0.86988349,  0.97942026,  0.28590975],
       [ 0.7399584 ,  1.97493004,  0.6868177 ],
       [ 0.54296567,  1.18860767, -0.71713872],
       [-1.54975337, -1.6387413 ,  1.09455162],
       [ 1.79920566, -0.31273012,  1.54939231]])

In [96]:
arr.sort(1)

In [97]:
arr

array([[ 0.28590975,  0.86988349,  0.97942026],
       [ 0.6868177 ,  0.7399584 ,  1.97493004],
       [-0.71713872,  0.54296567,  1.18860767],
       [-1.6387413 , -1.54975337,  1.09455162],
       [-0.31273012,  1.54939231,  1.79920566]])

In [98]:
""" Unique and other set logic """

' Unique and other set logic '

In [100]:
# retourner les valeurs uniques triées d'un array
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [101]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [104]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [105]:
# verifier si une valeur existe dans un array en renvoyant un array de booleens. (np.in1d())
values = np.array([6,0,0,3,2,5,6])

In [106]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [107]:
""" Linear Algebra """

' Linear Algebra '

In [109]:
# Produit Matriciel
x = np.array([[1.,2.,3.],[4.,5.,6.]])

In [110]:
y = np.array([[6.,23.],[-1,7],[8,9]])

In [111]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [112]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [113]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [114]:
# @ symbol : infix operator
x @ np.ones(3)

array([  6.,  15.])

In [115]:
""" PseudoRandom Number Generation"""

' PseudoRandom Number Generation'

In [116]:
# Un sample 4x4 depuis un standard normal distribution
samples = np.random.normal(size=(4,4))

In [117]:
samples

array([[-0.49943644,  0.29756041,  0.43506743, -1.14104152],
       [ 0.27607518,  1.73231349,  0.47581082,  0.72594582],
       [-0.18357506,  0.24250463,  1.04418031, -0.26465077],
       [ 0.62485578, -1.29326615, -1.27108125,  0.85148311]])