In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
# listes imbriquées peuvent être converties en array multidimensionnelle
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# dimensions d'un array
arr2.ndim

2

In [9]:
arr2.shape

(2, 4)

In [10]:
""" créer des arrays vides """
#arrays de 0 à une dimension
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [12]:
#arrays de 0 à 3 dimensions et 6 elts
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [21]:
# arrrays d'elts non identifiés ( pas toujours des zeros)
np.empty((2,3,2)) 

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [24]:
#creer un array de 1
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
# arange() : permettant de creer des elts suivants une intervalle
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# creer une matrice identité (0s et diagonale de 1s)
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [28]:
""" Data types for ndarrays """

' Data types for ndarrays '

In [29]:
# decider le type d'un array
arr1 = np.array([1,2,3],dtype=np.float64)

In [30]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [31]:
arr1

array([ 1.,  2.,  3.])

In [32]:
arr2

array([1, 2, 3])

In [33]:
# convertir un dtype vers un autre
arr = np.array([1,2,3,4,5])

In [35]:
arr.dtype

dtype('int32')

In [36]:
float_arr = arr.astype(np.float64)

In [37]:
float_arr.dtype

dtype('float64')

In [38]:
# Caster des Strings en nombre
numeric_strings = np.array(['1.25','6','-7.9'],dtype=np.string_)

In [39]:
numeric_strings.astype(np.float64)

array([ 1.25,  6.  , -7.9 ])

In [40]:
""" Arithmetic with Numpy array """

' Arithmetic with Numpy array '

In [41]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [42]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [43]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [46]:
# operation d'une variable sur chaque element de l'array

In [47]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [48]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [49]:
# comparaison entre 2 arrays (renvoie des booleens pas elts comparés)
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [50]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [52]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [53]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [54]:
""" Basic indexing and Slicing """

' Basic indexing and Slicing '

In [55]:
arr = np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5]

5

In [58]:
arr[5:8]

array([5, 6, 7])

In [61]:
# Change chaque élément du slicing par la valeur affectée
arr[5:8] = 12

In [60]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [62]:
# on modifie directement les arrays
arr_slice = arr[5:8]

In [63]:
arr_slice

array([12, 12, 12])

In [64]:
arr_slice[1] = 666

In [65]:
arr

array([  0,   1,   2,   3,   4,  12, 666,  12,   8,   9])

In [66]:
# assigner tous les elts de l'array
arr_slice[:]

array([ 12, 666,  12])

In [67]:
arr[:]

array([  0,   1,   2,   3,   4,  12, 666,  12,   8,   9])

In [68]:
# trouver un bloc dans un array 2 dimensions
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
arr2d[2]

array([7, 8, 9])

In [70]:
# Trouver un elt individuel dans un array à 2 dimensions
arr2d[0][2]

3

In [71]:
arr2d[1][2]

6

In [72]:
# recuperer des elts ou sub-array d'un array multidimensionnel
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [73]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
#copier une fraction d'un array sans alterer l'original
old_values = arr3d[0].copy()

In [76]:
arr3d[0] = 42

In [78]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0] = old_values

In [80]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])