In [11]:
import numpy as np

In [12]:
# Slicing 2d (page 97) 
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [20]:
arr2d[1,:2]

array([4, 5])

In [22]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [23]:
arr2d[:2,1:] = 0

In [24]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [25]:
"""  Boolean Indexing """
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [26]:
data = np.random.randn(7,4)

In [27]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [28]:
data

array([[ 0.98510167, -1.31831775,  1.17051218,  0.9266913 ],
       [-1.60325112,  0.58468009, -1.31396361, -1.01227075],
       [-0.46785904, -1.09719866,  0.29365928,  0.92638025],
       [ 0.63891405,  1.77161057,  0.28674728,  1.13495827],
       [-2.98599128, -0.13842496,  0.37247137,  0.62400023],
       [-0.33158781, -1.82028511,  1.92957861,  0.77065319],
       [ 0.3986678 ,  0.416259  ,  1.15653715, -0.56223323]])

In [30]:
#Trouver si un elt correspond à l'array
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [32]:
# Renvoyer un ensemble d'elements suivant une séquence de booléen (Renvoie les lignes correspondantes à true)
data[names == 'Bob']

array([[ 0.98510167, -1.31831775,  1.17051218,  0.9266913 ],
       [ 0.63891405,  1.77161057,  0.28674728,  1.13495827]])

In [33]:
# chercher les colonnes corespondantes ou names == 'Bob' avec slicing
data[names == 'Bob',2:]

array([[ 1.17051218,  0.9266913 ],
       [ 0.28674728,  1.13495827]])

In [34]:
data[names == 'Bob',3]

array([ 0.9266913 ,  1.13495827])

In [35]:
#Choisir tous les elts sauf 'Bob'
data[names!='Bob']

array([[-1.60325112,  0.58468009, -1.31396361, -1.01227075],
       [-0.46785904, -1.09719866,  0.29365928,  0.92638025],
       [-2.98599128, -0.13842496,  0.37247137,  0.62400023],
       [-0.33158781, -1.82028511,  1.92957861,  0.77065319],
       [ 0.3986678 ,  0.416259  ,  1.15653715, -0.56223323]])

In [36]:
    # ou avec le tilde ~
data[names!='Bob']


array([[-1.60325112,  0.58468009, -1.31396361, -1.01227075],
       [-0.46785904, -1.09719866,  0.29365928,  0.92638025],
       [-2.98599128, -0.13842496,  0.37247137,  0.62400023],
       [-0.33158781, -1.82028511,  1.92957861,  0.77065319],
       [ 0.3986678 ,  0.416259  ,  1.15653715, -0.56223323]])

In [37]:
#Renvoyer les données selon que names == Bob ou Will
mask = (names == 'Bob') | (names == 'Will')

In [39]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [38]:
data[mask]

array([[ 0.98510167, -1.31831775,  1.17051218,  0.9266913 ],
       [-0.46785904, -1.09719866,  0.29365928,  0.92638025],
       [ 0.63891405,  1.77161057,  0.28674728,  1.13495827],
       [-2.98599128, -0.13842496,  0.37247137,  0.62400023]])

In [40]:
# Passer toutes les données négatives à 0
data[data <0] = 0

In [41]:
data

array([[ 0.98510167,  0.        ,  1.17051218,  0.9266913 ],
       [ 0.        ,  0.58468009,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.29365928,  0.92638025],
       [ 0.63891405,  1.77161057,  0.28674728,  1.13495827],
       [ 0.        ,  0.        ,  0.37247137,  0.62400023],
       [ 0.        ,  0.        ,  1.92957861,  0.77065319],
       [ 0.3986678 ,  0.416259  ,  1.15653715,  0.        ]])

In [42]:
# Changer toute une ligne ou colonne
data[names != 'Joe'] =7

In [43]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.58468009,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  1.92957861,  0.77065319],
       [ 0.3986678 ,  0.416259  ,  1.15653715,  0.        ]])

In [45]:
""" Fancy Indexing   :  Indexer avec des arrays d'Integer"""

" Fancy Indexing   :  Indexer avec des arrays d'Integer"

In [46]:
arr = np.empty((8,4))

In [47]:
arr

array([[  2.26952853e-268,   1.86918699e-306,   1.69121096e-306,
          1.60218491e-306],
       [  9.34605716e-307,   1.42419938e-306,   7.56603881e-307,
          8.45603441e-307],
       [  1.42417221e-306,   1.60219306e-306,   6.23059726e-307,
          1.06811422e-306],
       [  1.42417221e-306,   1.37961641e-306,   8.06612192e-308,
          1.24610383e-306],
       [  1.69118108e-306,   8.06632139e-308,   1.20160711e-306,
          1.69119330e-306],
       [  8.90098127e-307,   1.95820216e-306,   7.56604561e-307,
          8.45590539e-307],
       [  1.11261298e-306,   6.23054633e-307,   9.34603679e-307,
          1.11261502e-306],
       [  1.86919513e-306,   1.11261570e-306,   1.42410974e-306,
          2.92300328e+048]])

In [48]:
for i in range(8):
    arr[i] = i

In [49]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [50]:
# selectionner un sous ensemble des lignes dans un ordre particulier
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [52]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [57]:
# Reformater l'array à partir d'un array 1-dimension
arr = np.arange(32)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [55]:
arr = arr.reshape((8,4))

In [56]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [58]:
# Extraire les elts precis depuis
arr[[1,5,7,2],[0,3,1,2]]

IndexError: too many indices for array

In [59]:
""" Transposer des arrays et échanger les axes """
# Transposée d'une matrice
arr = np.arange(15).reshape((3,5))

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [64]:
# swap des axes
arr = np.arange(16).reshape((2,2,4))

In [65]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr.swapaxes(0,0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])