In [1]:
""" Integer Indexes"""

' Integer Indexes'

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
ser = pd.Series(np.arange(3.))

In [6]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [7]:
ser[-1]

KeyError: -1

In [9]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [10]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [14]:
ser2[-1]

2.0

In [15]:
ser[:1]

0    0.0
dtype: float64

In [16]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [17]:
ser.iloc[:1]

0    0.0
dtype: float64

In [18]:
""" Arithmetic and Data Alignement"""

' Arithmetic and Data Alignement'

In [19]:
#Somme de 2 Series 

In [20]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','b','c','d'])

In [23]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [24]:
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [25]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [26]:
s1+s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [27]:
#oSomme DataFrame

In [29]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [30]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [31]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [32]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [33]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [34]:
#Somme de 2 Dataframe qui n'ont rien à voir
df1 = pd.DataFrame({'A':[1,2]})

In [35]:
df2 = pd.DataFrame({'B':[3,4]})

In [36]:
df1

A
0  1
1  2

In [37]:
df2

B
0  3
1  4

In [38]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [46]:
#Somme de 2 Dataframe avec un paramètre 'fill' pour considérer les NaN comme 0

In [40]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [41]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [42]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [43]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [44]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [45]:
#paramètre fill
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [47]:
#operation sur tout le dataframe
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [49]:
#rdiv() division inversée
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [50]:
#Parametre 'fill' avec une reindexation
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [51]:
""" Operations entre Dataframe et Series"""

' Opertaions entre Dataframe et Series'

In [52]:
arr = np.arange(12.).reshape((3,4))

In [53]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [54]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [55]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [56]:
#
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [57]:
series = frame.iloc[0]

In [59]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [60]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [61]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [62]:
#Somme Dataframe + Series
series2 = pd.Series(range(3),index=['b','e','f'])

In [63]:
series2

b    0
e    1
f    2
dtype: int32

In [64]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [65]:
series3 = frame['d']

In [66]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [67]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [69]:
#Operation sur les colonnes
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [70]:
""" Les 'Ufuncs' de Numpy s'applique aussi sur Pandas"""

" Les 'Ufuncs' de Numpy s'applique aussi sur Pandas"

In [71]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [72]:
frame

b         d         e
Utah    0.544330 -1.126870 -0.118776
Ohio    0.218240  0.594006 -0.645765
Texas  -1.174989 -0.922680 -0.189005
Oregon  0.139566  0.256939 -0.496239

In [73]:
np.abs(frame)

b         d         e
Utah    0.544330  1.126870  0.118776
Ohio    0.218240  0.594006  0.645765
Texas   1.174989  0.922680  0.189005
Oregon  0.139566  0.256939  0.496239

In [74]:
f = lambda x: x.max() - x.min()

In [75]:
frame.apply(f)

b    1.719319
d    1.720876
e    0.526989
dtype: float64

In [77]:
#utiliser le lambda sur les lignes
frame.apply(f,axis='columns')

Utah      1.671200
Ohio      1.239771
Texas     0.985983
Oregon    0.753177
dtype: float64

In [78]:
""" Sorting and Ranking """

' Sorting and Ranking '

In [79]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [80]:
#Tri lexicographic sur les index
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [81]:
# Tri de Dataset sur les axes
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [82]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [83]:
#Trier les colonnes
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [84]:
#Tri par orde décroissant
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [85]:
# Tri d'une Series par ses Valeurs
obj = pd.Series([4,7,-3,2])

In [86]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [87]:
#Trier un DataFrame suivant une colonne
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [88]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [89]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [90]:
#Tri par colonnes multiples
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7